import {EXTRA,filled,merge,closed,sla,reminders,scopeTickets,clinicRecap,localDay,opened} from './core.js?v=3';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const FORM='https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=8Sq2y8CkOEWdeGKInLNdYw1_rrxVxaFImLkzEWnt0GFUQUtJVFg2VzU5UEowM01JMUgzUUpKMTZPVi4u';
let rows=[],headers=[],refs=[],holidays=[],current='clinic',filter='',editing=null,busy=false,scope='assigned',mine=false,mrn='',statusSection='unresolved',workbookUrl='',ready=false;
let profile={name:'',email:'',clinics:[],role:''};try{profile={...profile,...JSON.parse(localStorage.getItem('mhsBillingProfile')||'{}')};}catch{}
const options={'Department Submitting Ticket:':2,'Patient Clinic:':3,'Urgency Level:':5,'Source of Inquiry:':6,'Task Type:':7,'Status:':10,'Was false verification of balance/charge given by Arietis?':14,'Patient Feedback/Service Recovery Flag:':15,'Source of Error:':16,'Outcome:':17};
function objects(v){return v.slice(1).filter(r=>filled(r[0])).map((r,index)=>({...Object.fromEntries(v[0].map((h,i)=>[h,r[i]??''])),_row:index}));}
async function run(fn){if(busy)return;busy=true;try{await fn();$('#message').textContent=`Updated ${new Date().toLocaleTimeString()} · All edits saved on Master`;$('#syncBadge').textContent='Sync every 30s';}catch(e){$('#message').textContent=e.message;}finally{busy=false;}}
async function initialize(){await Excel.run(async ctx=>{
  const master=ctx.workbook.worksheets.getItem('Master');const range=master.getUsedRange();range.load('values');await ctx.sync();
  const h=range.values[0].map(String);for(const name of EXTRA)if(!h.includes(name)){master.getCell(0,h.length).values=[[name]];h.push(name);}
  const tabs=ctx.workbook.worksheets;tabs.load('items/name');await ctx.sync();
  if(!tabs.items.some(x=>x.name==='_SyncState')){const s=tabs.add('_SyncState');s.getRange('A1:D1').values=[['Id','Baseline JSON','Override Fields JSON','Conflicts JSON']];s.visibility='Hidden';}
  if(!tabs.items.some(x=>x.name==='Settings')){const s=tabs.add('Settings');s.getRange('A1:B5').values=[['Setting','Value'],['Time zone','Pacific Standard Time'],['Business open','09:00'],['Business close','17:00'],['Weekly recap day','Friday']];s.getRange('D1').values=[['Holiday dates (YYYY-MM-DD)']];s.getRange('D2').values=[['']];}
  master.tables.load('items/name');await ctx.sync();if(!master.tables.items.length){const t=master.tables.add(master.getRangeByIndexes(0,0,range.values.length,h.length),true);t.name='BillingMaster';}
  else {master.tables.items[0].resize(master.getRangeByIndexes(0,0,range.values.length,h.length));}
  await ctx.sync();
});await refresh();}
async function refresh(){await Excel.run(async ctx=>{
  const m=ctx.workbook.worksheets.getItem('Master').getUsedRange();const r=ctx.workbook.worksheets.getItem('REF').getUsedRange();const s=ctx.workbook.worksheets.getItemOrNullObject('Settings');s.load('isNullObject');m.load('values');r.load('values');await ctx.sync();
  headers=m.values[0].map(String);rows=objects(m.values);refs=r.values.slice(1);holidays=[];
  if(!s.isNullObject){const v=s.getUsedRange();v.load('values');await ctx.sync();holidays=v.values.slice(1).map(x=>String(x[3]||'')).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x));workbookUrl=v.values[5]?.[1]||'';}
});render();}
async function sync(){await Excel.run(async ctx=>{
  const ws=ctx.workbook.worksheets.getItem('Master'),raw=ctx.workbook.worksheets.getItem('Raw Data'),state=ctx.workbook.worksheets.getItem('_SyncState');
  const mr=ws.getUsedRange(),rr=raw.getUsedRange(),sr=state.getUsedRange();mr.load('values');rr.load('values');sr.load('values');await ctx.sync();
  const mh=mr.values[0].map(String),rh=rr.values[0].map(String),index=new Map();
  mr.values.slice(1).forEach((r,i)=>{if(filled(r[0])){if(index.has(String(r[0])))throw Error('Duplicate Id in Master; sync stopped.');index.set(String(r[0]),i+1);}});
  const states=new Map(sr.values.slice(1).filter(r=>filled(r[0])).map(r=>[String(r[0]),r]));let append=mr.values.length;
  const seen=new Set();for(const rawRow of rr.values.slice(1)){
    if(!filled(rawRow[0]))continue;const id=String(rawRow[0]);if(seen.has(id))throw Error('Duplicate Id in Raw Data; sync stopped.');seen.add(id);
  }
  for(const rawRow of rr.values.slice(1)){
    if(!filled(rawRow[0]))continue;const id=String(rawRow[0]),r=Object.fromEntries(rh.map((h,i)=>[h,rawRow[i]??'']));
    const pos=index.get(id),m=pos===undefined?{}:Object.fromEntries(mh.map((h,i)=>[h,mr.values[pos][i]??'']));
    const old=states.get(id),baseline=old?JSON.parse(old[1]||'{}'):{},overrides=old?JSON.parse(old[2]||'[]'):[];
    const out=merge(m,r,baseline);for(const key of overrides)out.next[key]=m[key]??'';
    if(closed(m))out.next['Status:']=m['Status:'];
    if(filled(m['Date of first reply from Arietis:']))out.next['Date of first reply from Arietis:']=m['Date of first reply from Arietis:'];
    const pending=new Set(old?JSON.parse(old[3]||'[]'):[]);out.conflicts.forEach(k=>pending.add(k));
    if(!filled(out.next['Owner Email']))out.next['Owner Email']=out.next.Email||'';
    if(closed(out.next)&&!closed(m)&&!filled(out.next['Closed At'])){out.next['Status:']=m['Status:']||'MHS - Submitted to Arietis';pending.add('Status: (close in add-in after inbox reconciliation)');}
    const grace=reminders(out.next,holidays);out.next['Reminder Flags']=[grace.needsFollowUp?'Needs follow-up beyond 3 business days':'',grace.pastDue?'No follow-up beyond 5 business days':'',grace.resolutionOverdue?'Resolution overdue beyond 6 business days':''].filter(Boolean).join('; ');
    const flags=sla(out.next,holidays);out.next['Confirmation Due']=flags.confirmation;out.next['Resolution Due']=flags.resolution;out.next['Escalation Flag']=flags.flags.join('; ');out.next['Sync Conflicts']=[...pending].join('; ');
    if(pos===undefined){ws.getRangeByIndexes(append,0,1,mh.length).values=[mh.map(h=>out.next[h]??'')];index.set(id,append++);}
    else for(let j=0;j<mh.length;j++)if(String(out.next[mh[j]]??'')!==String(mr.values[pos][j]??''))ws.getCell(pos,j).values=[[out.next[mh[j]]??'']];
    states.set(id,[id,JSON.stringify(r),JSON.stringify(overrides),JSON.stringify([...pending])]);
  }
  if(states.size)state.getRangeByIndexes(1,0,states.size,4).values=[...states.values()];
  ws.tables.load('items/name');await ctx.sync();if(ws.tables.items.length)ws.tables.items[0].resize(ws.getRangeByIndexes(0,0,append,mh.length));await ctx.sync();
});await refresh();}
function filtered(){return scopeTickets(rows,profile,{scope,mine,mrn,clinic:filter});}
function clinicOptions(){return [...new Set([...refs.map(r=>r[0]),...rows.map(r=>r['Patient Clinic:'])].filter(filled))];}
function ticketCard(r){const x=reminders(r,holidays),formal=sla(r,holidays);const badge=closed(r)?'Resolved / Closed':x.resolutionOverdue?'Resolution overdue':x.needsFollowUp?'Needs follow-up':x.awaiting?'Awaiting receipt':r['Status:']||'In progress';return `<article class="ticket"><div class="ticket-head"><span class="small meta">#${esc(r.Id)} · ${esc(r['Patient Clinic:'])}</span><span class="tag ${closed(r)?'good':x.resolutionOverdue||x.needsFollowUp?'warn':''}">${esc(badge)}</span></div><h3>${esc(r['Task Type:']||'Billing inquiry')}</h3><div class="ticket-details"><span>MRN ${esc(r['MRN:'])}</span><span>${esc(r['Patient:'])}</span><span>${esc(r['Urgency Level:']||'Normal')} priority</span></div><div class="ticket-foot"><div><p>${x.awaiting?'No vendor reply':filled(r['Date of first reply from Arietis:'])?'Receipt confirmed':'Receipt unrecorded'} · ${x.age} business days</p><p class="meta">Opened ${esc(localDay(opened(r))||'—')} · ${esc(r['Owner Email']||r.Email||'Unassigned')}</p></div><button data-id="${esc(r.Id)}">Update status <span aria-hidden="true">↗</span></button></div><details class="help" style="margin-top:10px"><summary>SLA dates</summary><p>Receipt: ${esc(formal.confirmation||'Vendor submission date needed')} · Resolution: ${esc(formal.resolution||'—')}</p></details>${x.pastDue||filled(r['Sync Conflicts'])?`<p class="flag">${esc([x.pastDue?'No documented follow-up within 5 business days':'',r['Sync Conflicts']?'Review sync conflicts: '+r['Sync Conflicts']:''].filter(Boolean).join(' · '))}</p>`:''}</article>`;}
function render(){
  document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===current);b.setAttribute('aria-pressed',String(b.dataset.view===current));});
  $('#pageTitle').textContent={clinic:'Clinic Dashboard',settings:'Your settings',recap:'Clinic Recaps',form:'Submit New Ticket'}[current];
  $('#pageSubtitle').textContent=current==='clinic'?(profile.clinics.length?profile.clinics.join(' & ')+' · ':'')+new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',weekday:'long',month:'long',day:'numeric'}).format(new Date()):{settings:'Set your default clinic view',recap:'A focused summary for each clinic',form:'Billing escalation'}[current];
  $('#profileName').textContent=profile.name||'Your profile';$('#profileRole').textContent=profile.role||'Set up in Settings';$('#profileInitials').textContent=profile.name?profile.name.split(/\s+/).map(s=>s[0]).slice(0,2).join('').toUpperCase():'—';
  if(current==='form'){$('#view').innerHTML=`<div class="actions"><button id="backDashboard">← Dashboard</button><a href="${FORM}" target="_blank" rel="noopener noreferrer">Open form in a new window ↗</a></div><iframe title="Billing escalation submission form" src="${FORM}&embed=true" width="640" height="480" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>`;$('#backDashboard').onclick=()=>{current='clinic';render();};return;}
  if(current==='settings'){
    $('#view').innerHTML=`<form id="profileForm" class="form-panel"><h2>Your profile</h2><div class="two"><label>Name<input name="name" value="${esc(profile.name)}" required></label><label>Email<input type="email" name="email" value="${esc(profile.email)}" required></label></div><label>Role<input name="role" value="${esc(profile.role)}" placeholder="Your clinic role" required></label><fieldset><legend>Assigned clinics</legend><div class="clinic-checks">${clinicOptions().map(c=>`<label class="check"><input type="checkbox" name="clinics" value="${esc(c)}" ${profile.clinics.includes(c)?'checked':''}>${esc(c)}</label>`).join('')||'<p class="help">Open this add-in in Excel to load clinic options from REF.</p>'}</div></fieldset><label>Cloud workbook URL<input type="url" name="workbookUrl" value="${esc(workbookUrl)}" placeholder="https://…"></label><div class="actions"><button class="primary">Save profile</button></div><p class="help">Profile settings stay on this browser/device. Workbook permissions control access. Add organization holidays in Settings column D.</p></form>`;
    $('#profileForm').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target),clinics=data.getAll('clinics');if(!clinics.length){$('#message').textContent='Select at least one assigned clinic.';return;}const url=String(data.get('workbookUrl')||'').trim();if(url&&!/^https:\/\//i.test(url)){$('#message').textContent='Use an HTTPS workbook URL.';return;}run(async()=>{if(url!==workbookUrl)await Excel.run(async ctx=>{ctx.workbook.worksheets.getItem('Settings').getRange('A6:B6').values=[['Workbook URL',url]];await ctx.sync();});const next={name:String(data.get('name')),email:String(data.get('email')).trim(),role:String(data.get('role')),clinics};localStorage.setItem('mhsBillingProfile',JSON.stringify(next));profile=next;workbookUrl=url;scope='assigned';mine=false;filter='';mrn='';current='clinic';render();});};return;
  }
  if(current==='recap'){renderRecap();return;}
  const a=filtered(),active=a.filter(r=>!closed(r)),awaiting=active.filter(r=>reminders(r,holidays).awaiting),past=active.filter(r=>reminders(r,holidays).pastDue),follow=active.filter(r=>reminders(r,holidays).needsFollowUp),overdue=active.filter(r=>reminders(r,holidays).resolutionOverdue);
  const sections={unresolved:active,awaiting,past,follow,overdue,all:a},labels={unresolved:'Unresolved',awaiting:'Awaiting Reply',follow:'Needs Follow-up',past:'Past Due',overdue:'Resolution Overdue',all:'All statuses'};
  $('#view').innerHTML=`<div class="actions"><button class="primary" id="newTicket">+ Submit New Ticket</button><button id="generateRecap">✉ Generate recap</button></div>${!profile.clinics.length?'<p class="notice" style="margin-top:16px">Choose your assigned clinics in Settings to populate this dashboard.</p>':''}<div class="filters"><label>Ticket scope<select id="scope"><option value="assigned" ${scope==='assigned'?'selected':''}>My assigned clinics</option><option value="all" ${scope==='all'?'selected':''}>All tickets / all clinics</option></select></label><label>Clinic<select id="clinicFilter"><option value="">${scope==='assigned'?'All assigned clinics':'All clinics'}</option>${clinicOptions().filter(c=>scope==='all'||profile.clinics.includes(c)).map(c=>`<option value="${esc(c)}" ${filter===c?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>Find by MRN<input id="mrnFilter" value="${esc(mrn)}" placeholder="Exact MRN"></label><label class="mine-filter"><input type="checkbox" id="mine" ${mine?'checked':''}>My Tickets</label></div><div class="metrics"><button class="metric" data-section="unresolved"><p>Open tickets</p><strong>${active.length}</strong><small>Across selected clinics</small></button><button class="metric" data-section="follow"><p>Need follow-up</p><strong>${follow.length}</strong><small>Receipt unconfirmed after day 3</small></button><button class="metric" data-section="overdue"><p>Resolution overdue</p><strong>${overdue.length}</strong><small>Incomplete after day 6</small></button></div><div class="dashboard-body"><section><div class="status-pills">${Object.entries(labels).map(([key,label])=>`<button data-section="${key}" aria-pressed="${statusSection===key}">${label} · ${sections[key].length}</button>`).join('')}</div><div class="list-heading"><span>${labels[statusSection]}</span><span>${sections[statusSection].length} tickets · ${mine?'Assigned to you':'All owners'}</span></div><div class="ticket-list">${sections[statusSection].length?sections[statusSection].map(ticketCard).join(''):'<p class="empty">No tickets match this view.</p>'}</div></section><aside class="rail"><div class="box"><h3>Clinic recap</h3><p class="help">A clear handoff at the start and end of each day.</p><button data-recap="am">☀ AM · Open tickets</button><button data-recap="pm">☾ PM · Resolved today</button></div><div class="box"><h3>Response timelines</h3><div class="rule"><span>Receipt SLA</span><strong>2 business days</strong></div><div class="rule"><span>Resolution SLA</span><strong>5 business days</strong></div><hr><div class="rule"><span>Receipt reminder</span><strong>After day 3</strong></div><div class="rule"><span>Resolution reminder</span><strong>After day 6</strong></div><p class="help">Weekends and clinic holidays excluded.</p></div></aside></div>`;
  $('#newTicket').onclick=()=>{current='form';render();};$('#generateRecap').onclick=()=>{current='recap';render();};document.querySelectorAll('[data-recap]').forEach(b=>b.onclick=()=>{recapMode=b.dataset.recap;recapClinic=filter||profile.clinics[0]||'';current='recap';render();});
  $('#scope').onchange=e=>{scope=e.target.value;filter='';render();};$('#clinicFilter').onchange=e=>{filter=e.target.value;render();};$('#mrnFilter').onchange=e=>{mrn=e.target.value;render();};$('#mine').onchange=e=>{mine=e.target.checked;render();};document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{statusSection=b.dataset.section;render();});document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>edit(b.dataset.id));
}
let recapClinic='',recapMode='am';
function renderRecap(){const clinics=clinicOptions();if(!clinics.includes(recapClinic))recapClinic=profile.clinics[0]||clinics[0]||'';const recap=clinicRecap(rows,recapClinic,recapMode,holidays,undefined,workbookUrl);const recipient=refs.find(r=>r[0]===recapClinic)?.[1]||'';
  $('#view').innerHTML=`<div class="recap-controls"><label>Clinic<select id="recapClinic">${clinics.map(c=>`<option ${c===recapClinic?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>Recap<select id="recapMode"><option value="am" ${recapMode==='am'?'selected':''}>AM · Open tickets</option><option value="pm" ${recapMode==='pm'?'selected':''}>PM · Resolved today</option></select></label><button id="copyRecap">Copy template</button></div><p class="recap-meta meta">To: ${esc(recipient||'Clinic email not configured')}<br>Subject: ${esc(recap.subject)}</p><section id="recapPreview" class="recap-preview">${recap.html}</section><p class="help">Preview only. This does not send email.</p><details class="recap-source"><summary>HTML template</summary><textarea id="recapHtml" aria-label="HTML email template" readonly>${esc(recap.html)}</textarea></details>`;
  $('#recapClinic').onchange=e=>{recapClinic=e.target.value;renderRecap();};$('#recapMode').onchange=e=>{recapMode=e.target.value;renderRecap();};$('#copyRecap').onclick=async()=>{try{await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([recap.html],{type:'text/html'}),'text/plain':new Blob([$('#recapPreview').innerText],{type:'text/plain'})})]);$('#message').textContent='Email template copied. Paste into your Microsoft 365 email.';}catch{$('.recap-source').open=true;$('#recapHtml').select();$('#message').textContent='Select/copy the HTML template below; clipboard access is unavailable.';}};
}

function edit(id){editing=rows.find(r=>String(r.Id)===id);$('#editorTitle').textContent='Update ticket #'+id;const fields=headers.filter(h=>!['Id','Start time','Completion time','Confirmation Due','Resolution Due','Escalation Flag','Reminder Flags','Sync Conflicts','Column1','Date of first reply from Arietis:','Last Reply At','Closed At'].includes(h));$('#fields').innerHTML=fields.map(h=>{const v=editing[h]??'';const opts=options[h]===undefined?null:[...new Set(refs.map(r=>r[options[h]]).filter(x=>filled(x)&&x!=='[Free Text]'))];let control;if(opts&&h!=='Task Type:'){const all=[...new Set(['',v,...opts])];control=`<select name="${esc(h)}">${all.map(x=>`<option ${String(x)===String(v)?'selected':''}>${esc(x)}</option>`).join('')}</select>`;}else control=`<textarea name="${esc(h)}">${esc(v)}</textarea>`;return `<label>${esc(h)}${control}</label>`;}).join('');$('#editor').showModal();}
async function save(){const fd=new FormData($('#editForm'));await Excel.run(async ctx=>{
  const ws=ctx.workbook.worksheets.getItem('Master'),range=ws.getUsedRange(),state=ctx.workbook.worksheets.getItem('_SyncState'),sr=state.getUsedRange();range.load('values');sr.load('values');await ctx.sync();
  const h=range.values[0].map(String),pos=range.values.findIndex((r,i)=>i>0&&String(r[0])===String(editing.Id));if(pos<0)throw Error('Ticket missing; refresh.');
  const changes=[...fd].filter(([key,v])=>String(v)!==String(editing[key]??''));for(const [key] of changes)if(String(range.values[pos][h.indexOf(key)]??'')!==String(editing[key]??''))throw Error('Another editor changed this field; refresh before saving.');
  const newStatus=fd.get('Status:');const closing=/^(Closed|Resolved)\b/.test(String(newStatus));if(closed(editing)&&newStatus!==editing['Status:'])throw Error('Reopening needs an explicit reviewed workflow.');
  if(closing&&!closed(editing)&&!filled(fd.get('Date of Resolution:')))throw Error('Enter resolution date before closing.');
  for(const [key,v] of changes)ws.getCell(pos,h.indexOf(key)).values=[[v]];
  if(closing&&!closed(editing))ws.getCell(pos,h.indexOf('Closed At')).values=[[new Date().toISOString()]];
  const sp=sr.values.findIndex((r,i)=>i>0&&String(r[0])===String(editing.Id));const old=sp<0?[]:JSON.parse(sr.values[sp][2]||'[]');const override=[...new Set([...old,...changes.map(x=>x[0])])];
  const stateRow=sp<0?[String(editing.Id),'{}',JSON.stringify(override),'[]']:[...sr.values[sp]];stateRow[2]=JSON.stringify(override);stateRow[3]='[]';state.getRangeByIndexes(sp<0?sr.values.length:sp,0,1,4).values=[stateRow];ws.getCell(pos,h.indexOf('Sync Conflicts')).values=[['']];await ctx.sync();
});$('#editor').close();await refresh();}
function bindUI(){
 $('#setup').onclick=()=>run(initialize);$('#refresh').onclick=()=>run(refresh);$('#sync').onclick=()=>run(sync);
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{current=b.dataset.view;render();});
 $('#cancel').onclick=()=>$('#editor').close();$('#editForm').onsubmit=e=>{e.preventDefault();run(save);};
}
render();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{current=b.dataset.view;render();});
Office.onReady(info=>{if(info.host!==Office.HostType.Excel){render();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{current=b.dataset.view;render();});return;}
 ready=true;$('#syncBadge').textContent='Sync every 30s';bindUI();run(initialize);
 setInterval(()=>{if(ready&&!busy&&!$('#editor').open&&current!=='settings'&&!document.activeElement?.matches('input,textarea,select'))run(sync);},30000);
});
