import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {stripTypeScriptTypes} from 'node:module';
const source=stripTypeScriptTypes(fs.readFileSync(new URL('../office-scripts/Automation.ts',import.meta.url),'utf8'));
function sheet(values){return {values,getUsedRange(){return {getValues:()=>this.values};},getRangeByIndexes(row,col,n,m){return {setValues:data=>{data.forEach((r,i)=>{this.values[row+i]??=[];r.forEach((v,j)=>this.values[row+i][col+j]=v);});}};},getTables(){return [];}};}
const h=['Id','Email','Patient Clinic:','MRN:','Notes','Status:','Date of first reply from Arietis:','Owner Email','Vendor Conversation ID','Submitted to Vendor At','Last Reply At','Closed At','Confirmation Due','Resolution Due','Escalation Flag','Sync Conflicts'];
function fixture(){const record=[31,'owner@example.com','San Rafael - CA','00123','Preserve','MHS - Submitted to Arietis','','owner@example.com','conversation-31','2026-10-02','','','','','',''];const sheets={Master:sheet([h,[...record]]),'Raw Data':sheet([h,[...record]]),'_SyncState':sheet([['Id','Baseline JSON','Override Fields JSON','Conflicts JSON']]),Settings:sheet([['Setting','Value','','Holiday dates'],['Time zone','Pacific Standard Time','','2026-10-05']])};const context=vm.createContext({Date,JSON,Set,Error,Number});vm.runInContext(source+';globalThis.run=main;',context);return {sheets,run:(op,payload='[]',today='2026-10-07')=>JSON.parse(context.run({getWorksheet:n=>sheets[n]},op,today,payload,'open'))};}
test('actual automation preserves blank overwrite and sync is idempotent',()=>{const f=fixture();f.run('sync');f.sheets['Raw Data'].values[1][2]='';f.sheets['Raw Data'].values[1][3]='';f.sheets['Raw Data'].values[1][4]='';f.run('sync');assert.equal(f.sheets.Master.values[1][3],'00123');assert.equal(f.sheets.Master.values[1][4],'Preserve');const before=JSON.stringify(f.sheets.Master.values);f.run('sync');assert.equal(JSON.stringify(f.sheets.Master.values),before);assert.equal(f.sheets.Master.values[1][12],'2026-10-07');});
test('actual script min/max replies with retries, wrong sender and unmatched conversation',()=>{const f=fixture();const replies=[{conversationId:'conversation-31',sender:'patientbilling@arietishealth.com',receivedAt:'2026-10-06T18:00:00Z',messageId:'late'},{conversationId:'conversation-31',sender:'patientbilling@arietishealth.com',receivedAt:'2026-10-05T18:00:00Z',messageId:'early'},{conversationId:'other',sender:'patientbilling@arietishealth.com',receivedAt:'2026-10-06T18:00:00Z',messageId:'unknown'}];const r=f.run('reply',JSON.stringify(replies));assert.equal(f.sheets.Master.values[1][6],'2026-10-05T18:00:00Z');assert.equal(f.sheets.Master.values[1][10],'2026-10-06T18:00:00Z');assert.deepEqual(r.unmatched,['unknown']);const before=JSON.stringify(f.sheets.Master.values);f.run('reply',JSON.stringify(replies));assert.equal(JSON.stringify(f.sheets.Master.values),before);});
test('reply after closure ignored; prior late-processed reply retained',()=>{const f=fixture();f.sheets.Master.values[1][5]='Resolved (Corrective Action Complete)';f.sheets.Master.values[1][11]='2026-10-06T20:00:00Z';f.run('reply',JSON.stringify([{conversationId:'conversation-31',sender:'patientbilling@arietishealth.com',receivedAt:'2026-10-07T18:00:00Z',messageId:'after'},{conversationId:'conversation-31',sender:'patientbilling@arietishealth.com',receivedAt:'2026-10-06T19:00:00Z',messageId:'before'}]));assert.equal(f.sheets.Master.values[1][10],'2026-10-06T19:00:00Z');});
test('digest omits patient identifiers and notes',()=>{const f=fixture();const s=JSON.stringify(f.run('digest'));assert.ok(!s.includes('00123'));assert.ok(!s.includes('Preserve'));assert.ok(s.includes('owner@example.com'));});
