/* Generated by scripts/dataverse-setup.mjs */
window.BE_DATAVERSE = {
  "sets": {
    "mhs_ticket": "mhs_tickets",
    "mhs_ticketactivity": "mhs_ticketactivities",
    "mhs_setting": "mhs_settings",
    "mhs_holiday": "mhs_holidays",
    "mhs_refoption": "mhs_refoptions"
  }
};
